### ISSUE TITLE
GIVE ALL BUG{public}

### ISSUE THREAD

**Issue by keqingyyds** [YuukiPS/DockerGS#44]
> Exception in thread "Thread-36" java.lang.IndexOutOfBoundsException: Index -1 out of bounds for length 6
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
        at java.base/java.util.Objects.checkIndex(Objects.java:359)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at emu.grasscutter.game.avatar.Avatar.unlockConstellation(Avatar.java:898)
        at emu.grasscutter.game.avatar.Avatar.forceConstellationLevel(Avatar.java:948)
        at emu.grasscutter.command.commands.GiveCommand.makeAvatar(GiveCommand.java:67)
        at emu.grasscutter.command.commands.GiveCommand.giveAllAvatars(GiveCommand.java:81)
        at emu.grasscutter.command.commands.GiveCommand.giveAll(GiveCommand.java:271)
        at emu.grasscutter.command.commands.GiveCommand.execute(GiveCommand.java:373)
        at emu.grasscutter.command.CommandMap.lambda$invoke$0(CommandMap.java:323)
        at java.base/java.lang.Thread.run(Thread.java:833)
It looks like a bug in the task branch. I don't have the source code to fix it. Can you fix it?

**Comment by akbaryahya** [comment]
source https://github.com/YuukiPS/Grasscutters-Original
